name = "Tancmeystery"
author = "ivanlabudev977"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0edde1aa566d971ffb180ad0d4089cb3c29f275eadc9a1ed4401f0482dee47be"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
