name = "Tancmeystery"
author = "ivanlabudev977"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe4fd9b851d2e36e08417c44e4eee13bdbd2d08c7d1ce6e46858fab8942276cc"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
