name = "Tancmeystery"
author = "ivanlabudev977"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "117cc309a1759c8dc13b7a8db174de3c21c90a10dcd4cf944b888df99fa11af7"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
